# Generated by Django 5.2 on 2025-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Модель машины')),
                ('company', models.CharField(max_length=20, verbose_name='Компания производитель')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото машины')),
                ('type', models.CharField(max_length=20, verbose_name='Тип машина')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('registration_type', models.CharField(choices=[('primary', 'Первичная регистрация'), ('secondary', 'Вторичная регистрация')], max_length=10, verbose_name='Регистрация')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('motor', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('KPP', models.CharField(max_length=20, verbose_name='КПП')),
                ('fuel', models.CharField(max_length=20, verbose_name='Тип топлива')),
                ('drive', models.CharField(max_length=20, verbose_name='Ведущая ось(Привод)')),
                ('mileage', models.CharField(max_length=20, verbose_name='Показания одометра (Пробег)')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('VIN_code', models.CharField(max_length=20, verbose_name='VIN код')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя Фамилия')),
                ('phone_number', models.IntegerField(verbose_name='Ваш номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка на покупку авто',
                'verbose_name_plural': 'Заявка на покупку авто',
            },
        ),
    ]
