# Generated by Django 5.2 on 2025-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_carphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='contribution',
            field=models.CharField(default=1, max_length=20, verbose_name='Первоначальный взнос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кредит'),
        ),
        migrations.AddField(
            model_name='car',
            name='state',
            field=models.CharField(default=1, max_length=20, verbose_name='Состояние'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='title_price',
            field=models.CharField(default=1, max_length=20, verbose_name='В месячный платеж'),
            preserve_default=False,
        ),
    ]
