# Generated by Django 5.2 on 2025-04-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_car_contribution_car_credit_car_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='credit',
        ),
    ]
