# Generated by Django 5.2 on 2025-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_car_time_alter_car_title_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=1, verbose_name='В наличие'),
            preserve_default=False,
        ),
    ]
