# Generated by Django 5.2 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_car_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('locations', models.CharField(max_length=40, verbose_name='Локация')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
    ]
