# Generated by Django 5.2 on 2025-04-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
