# Generated by Django 5.2 on 2025-04-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='img',
        ),
    ]
